from app.models.schemas import Rule
from app.ingestion.rule_store import RuleStore

SEED_RULES: list[Rule] = [
    Rule(id="FDCPA-809", citation="15 U.S.C. § 1692g", severity="critical",
         agent_must=["provide written validation notice within 5 days of initial contact"],
         agent_must_not=["continue collection after written dispute without sending validation"],
         role_tag="all", trigger_labels=["Debt Dispute", "Right to Validation Request"],
         text="Upon receiving a written dispute, the debt collector must cease collection until it obtains verification of the debt and mails it to the consumer. A validation notice must be sent within 5 days of initial contact."),
    Rule(id="FDCPA-805", citation="15 U.S.C. § 1692c", severity="high",
         agent_must=["cease communication upon written request"],
         agent_must_not=["contact consumer after cease-and-desist received",
                         "contact consumer at inconvenient times (before 8am or after 9pm)"],
         role_tag="all", trigger_labels=["Cease and Desist Request", "Bankruptcy Notification"],
         text="A debt collector must not communicate with a consumer after receiving written notice to cease communication, except to notify of specific legal actions."),
    Rule(id="FDCPA-806", citation="15 U.S.C. § 1692d", severity="critical",
         agent_must=["maintain professional and respectful tone throughout conversation"],
         agent_must_not=["harass, oppress, or abuse the consumer",
                         "use obscene or profane language",
                         "make repeated phone calls to annoy"],
         role_tag="all", trigger_labels=["Financial Hardship", "Cease and Desist Request"],
         text="A debt collector may not engage in any conduct the natural consequence of which is to harass, oppress, or abuse any person in connection with the collection of a debt."),
    Rule(id="FDCPA-807", citation="15 U.S.C. § 1692e", severity="critical",
         agent_must=["accurately state the debt amount, creditor name, and collection status"],
         agent_must_not=["make false or misleading representations",
                         "misrepresent the debt amount or character",
                         "threaten legal action not actually intended or authorized"],
         role_tag="all", trigger_labels=["Debt Dispute", "Fraud Claim"],
         text="A debt collector may not use any false, deceptive, or misleading representation or means in connection with the collection of any debt."),
    Rule(id="FDCPA-808", citation="15 U.S.C. § 1692f", severity="high",
         agent_must=["only collect amounts expressly authorized by the agreement or permitted by law"],
         agent_must_not=["collect unauthorized fees, interest, or charges",
                         "accept postdated checks by more than 5 days without notice"],
         role_tag="all", trigger_labels=["Payment Plan Request"],
         text="A debt collector may not use unfair or unconscionable means to collect a debt, including collecting amounts not expressly authorized by the agreement or permitted by law."),
    Rule(id="CFPB-HARDSHIP-01", citation="CFPB Bulletin 2013-07", severity="high",
         agent_must=["inform consumer about available hardship or assistance programs",
                     "document hardship claim in account notes"],
         agent_must_not=["deny existence of hardship or payment assistance programs",
                         "apply pressure tactics to consumer experiencing financial distress"],
         role_tag="all", trigger_labels=["Financial Hardship", "Payment Plan Request"],
         text="Servicers must have reasonable policies and procedures to identify consumers experiencing financial difficulty and must provide meaningful information about available assistance and hardship programs."),
    Rule(id="BANKRUPTCY-362", citation="11 U.S.C. § 362 (Automatic Stay)", severity="critical",
         agent_must=["immediately cease all collection activity upon bankruptcy notification",
                     "note bankruptcy filing in account and escalate to compliance team"],
         agent_must_not=["continue collection calls or letters after bankruptcy notice",
                         "demand or accept payment on pre-petition debt after bankruptcy notice"],
         role_tag="senior", trigger_labels=["Bankruptcy Notification"],
         text="The automatic stay under 11 U.S.C. § 362 prohibits any act to collect or recover a pre-petition debt. Upon notification of bankruptcy, all collection activity must immediately and completely cease."),
    Rule(id="FCRA-605", citation="15 U.S.C. § 1681c", severity="high",
         agent_must=["verify consumer identity using at least two identification factors before discussing account",
                     "document verification method in call notes"],
         agent_must_not=["discuss account details or balances with an unverified caller",
                         "bypass or skip identity verification steps"],
         role_tag="all", trigger_labels=["Identity Verification Failure", "Fraud Claim"],
         text="Consumer reporting agencies and furnishers must maintain reasonable procedures to verify consumer identity before disclosing or acting on account information."),
    Rule(id="FCRA-623", citation="15 U.S.C. § 1681s-2", severity="high",
         agent_must=["investigate disputed information within 30 days",
                     "correct, delete, or block inaccurate information after investigation",
                     "notify consumer of investigation outcome"],
         agent_must_not=["furnish information known or suspected to be inaccurate",
                         "ignore or dismiss a consumer dispute"],
         role_tag="senior", trigger_labels=["Account Closure Request", "Fraud Claim"],
         text="Furnishers of information to consumer reporting agencies have a duty to investigate consumer disputes and correct or delete inaccurate, incomplete, or unverifiable information."),
    Rule(id="CFPB-COMPLAINT-01", citation="CFPB Regulation 12 CFR 1024.35", severity="medium",
         agent_must=["acknowledge the complaint and provide a reference or case number",
                     "escalate to a supervisor or compliance team when consumer requests it",
                     "document all complaint details in the account notes"],
         agent_must_not=["dismiss or minimize the consumer's complaint",
                         "refuse a reasonable escalation request",
                         "fail to document the complaint"],
         role_tag="all", trigger_labels=["Complaint Escalation"],
         text="Servicers must maintain accessible and effective complaint processes, acknowledge complaints promptly with a reference number, and escalate unresolved issues through proper compliance channels."),
]


def seed(store: RuleStore, force: bool = False) -> int:
    """Idempotently seed rules. Returns number of rules inserted."""
    inserted = 0
    for rule in SEED_RULES:
        if force or not store.rule_exists(rule.id):
            store.add_rule(rule)
            inserted += 1
    return inserted
